### ISSUE TITLE
"[" was not closed

### ISSUE THREAD

**Issue by qwertyuiopasdfghjklzxcn** [jdjin3000/PRG-MoE#3]
"[" was not closed in module/trainer.py at line 248, col 36 and line 384, col36

**Comment by jdjin3000** [comment]
I've found and fixed the error where a single parenthesis was incorrectly placed. 

Thank you for pointing it out to me.

**Comment by jdjin3000** [comment]
`pair_window_idx[max(0, int((end_t - 1) * end_t) / 2), int(end_t * (end_t + 1) / 2) - window_constraint):int(end_t * (end_t + 1) / 2)] = 1`

`pair_window_idx[max(0, int((end_t - 1) * end_t / 2), int(end_t * (end_t + 1) / 2) - window_constraint):int(end_t * (end_t + 1) / 2)] = 1`

I've found and fixed the error where a single parenthesis was incorrectly placed.

Thank you for pointing it out to me.
